import React from "react";
import type { Metadata } from "next";
import { Sometype_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/contexts/AuthContext";

const font = Sometype_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={`${font.className} bg-default-primary`}>
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
